ci: configuracao inicial de circleci parte 5

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -133,184 +133,184 @@ steps:
         }
 
 
-        check_workflow_status () {
-          URL="https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}"
-          fetch $URL /tmp/workflow.json
-          export WORKFLOW_STATUS=$(jq -r '.status' /tmp/workflow.json)
-          export CIRCLE_PIPELINE_NUMBER=$(jq -r '.pipeline_number' /tmp/workflow.json)
-          echo "This job is passing, however another job in workflow is ${WORKFLOW_STATUS}"
+        #check_workflow_status () {
+        #  URL="https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}"
+        #  fetch $URL /tmp/workflow.json
+        #  export WORKFLOW_STATUS=$(jq -r '.status' /tmp/workflow.json)
+        #  export CIRCLE_PIPELINE_NUMBER=$(jq -r '.pipeline_number' /tmp/workflow.json)
+        #  echo "This job is passing, however another job in workflow is ${WORKFLOW_STATUS}"
 
-          if [ "<<parameters.job_type>>" != "deployment" ]; then
-              # deployments are special, cause they pass or fail alone.
-              # but jobs are stuck togehter, and they must respect status of workflow
-              if [[ "$WORKFLOW_STATUS" == "fail"* ]]; then
-                export JIRA_BUILD_STATUS="failed"
-              fi
-          fi
-        }
-
-
-        generate_json_payload_build () {
-          iso_time=$(date '+%Y-%m-%dT%T%z'| sed -e 's/\([0-9][0-9]\)$/:\1/g')
-          echo {} | jq \
-          --arg time_str "$(date +%s)" \
-          --arg lastUpdated "${iso_time}" \
-          --arg pipelineNumber "${CIRCLE_PIPELINE_NUMBER}" \
-          --arg projectName "${CIRCLE_PROJECT_REPONAME}" \
-          --arg state "${JIRA_BUILD_STATUS}" \
-          --arg jobName "${CIRCLE_JOB}" \
-          --arg buildNumber "${CIRCLE_BUILD_NUM}" \
-          --arg url "${CIRCLE_BUILD_URL}" \
-          --arg workflowUrl "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
-          --arg commit "${CIRCLE_SHA1}" \
-          --arg refUri "${CIRCLE_REPOSITORY_URL}/tree/${CIRCLE_BRANCH}" \
-          --arg repositoryUri "${CIRCLE_REPOSITORY_URL}" \
-          --arg branchName "${CIRCLE_BRANCH}" \
-          --arg workflowId "${CIRCLE_WORKFLOW_ID}" \
-          --arg repoName "${CIRCLE_PROJECT_REPONAME}" \
-          --arg display "${CIRCLE_PROJECT_REPONAME}"  \
-          --arg description "${CIRCLE_PROJECT_REPONAME} #${CIRCLE_BUILD_NUM} ${CIRCLE_JOB}" \
-          --argjson issueKeys "${ISSUE_KEYS}" \
-          '
-          ($time_str | tonumber) as $time_num |
-          {
-            "builds": [
-              {
-                "schemaVersion": "1.0",
-                "pipelineId": $projectName,
-                "buildNumber": $pipelineNumber,
-                "updateSequenceNumber": $time_str,
-                "displayName": $display,
-                "description": $description,
-                "url": $workflowUrl,
-                "state": $state,
-                "lastUpdated": $lastUpdated,
-                "issueKeys": $issueKeys
-              }
-            ]
-          }
-          ' > /tmp/jira-status.json
-        }
+        #  if [ "<<parameters.job_type>>" != "deployment" ]; then
+        #      # deployments are special, cause they pass or fail alone.
+        #      # but jobs are stuck togehter, and they must respect status of workflow
+        #      if [[ "$WORKFLOW_STATUS" == "fail"* ]]; then
+        #        export JIRA_BUILD_STATUS="failed"
+        #      fi
+        #  fi
+        #}
 
 
-        generate_json_payload_deployment () {
-          echo "Update Jira with status: ${JIRA_BUILD_STATUS} for ${CIRCLE_PIPELINE_NUMBER}"
-          iso_time=$(date '+%Y-%m-%dT%T%z'| sed -e 's/\([0-9][0-9]\)$/:\1/g')
-          echo {} | jq \
-          --arg time_str "$(date +%s)" \
-          --arg lastUpdated "${iso_time}" \
-          --arg state "${JIRA_BUILD_STATUS}" \
-          --arg buildNumber "${CIRCLE_BUILD_NUM}" \
-          --arg pipelineNumber "${CIRCLE_PIPELINE_NUMBER}" \
-          --arg projectName "${CIRCLE_PROJECT_REPONAME}" \
-          --arg url "${CIRCLE_BUILD_URL}" \
-          --arg commit "${CIRCLE_SHA1}" \
-          --arg refUri "${CIRCLE_REPOSITORY_URL}/tree/${CIRCLE_BRANCH}" \
-          --arg repositoryUri "${CIRCLE_REPOSITORY_URL}" \
-          --arg branchName "${CIRCLE_BRANCH}" \
-          --arg workflowId "${CIRCLE_WORKFLOW_ID}" \
-          --arg workflowUrl "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
-          --arg repoName "${CIRCLE_PROJECT_REPONAME}" \
-          --arg pipelineDisplay "#${CIRCLE_PIPELINE_NUMBER} ${CIRCLE_PROJECT_REPONAME}"  \
-          --arg deployDisplay "#${CIRCLE_PIPELINE_NUMBER}  ${CIRCLE_PROJECT_REPONAME} - <<parameters.environment>>"  \
-          --arg description "${CIRCLE_PROJECT_REPONAME} #${CIRCLE_PIPELINE_NUMBER} ${CIRCLE_JOB} <<parameters.environment>>" \
-          --arg envId "${CIRCLE_WORKFLOW_ID}-<<parameters.environment>>" \
-          --arg envName "<<parameters.environment>>" \
-          --arg envType "<<parameters.environment_type>>" \
-          --argjson issueKeys "${ISSUE_KEYS}" \
-          '
-          ($time_str | tonumber) as $time_num |
-          {
-            "deployments": [
-              {
-                "schemaVersion": "1.0",
-                "pipeline": {
-                  "id": $repoName,
-                  "displayName": $pipelineDisplay,
-                  "url": $workflowUrl
-                },
-                "deploymentSequenceNumber": $pipelineNumber,
-                "updateSequenceNumber": $time_str,
-                "displayName": $deployDisplay,
-                "description": $description,
-                "url": $url,
-                "state": $state,
-                "lastUpdated": $lastUpdated,
-                "associations": [
-                  {
-                    "associationType": "issueKeys",
-                    "values": $issueKeys
-                  },
-                  {
-                    "associationType": "serviceIdOrKeys",
-                    "values": ["<< parameters.service_id >>"]
-                  }
-                ],
-                "environment":{
-                  "id": $envId,
-                  "displayName": $envName,
-                  "type": $envType
-                }
-              }
-            ]
-          }
-          ' > /tmp/jira-status.json
-        }
+        #generate_json_payload_build () {
+        #  iso_time=$(date '+%Y-%m-%dT%T%z'| sed -e 's/\([0-9][0-9]\)$/:\1/g')
+        #  echo {} | jq \
+        #  --arg time_str "$(date +%s)" \
+        #  --arg lastUpdated "${iso_time}" \
+        #  --arg pipelineNumber "${CIRCLE_PIPELINE_NUMBER}" \
+        #  --arg projectName "${CIRCLE_PROJECT_REPONAME}" \
+        #  --arg state "${JIRA_BUILD_STATUS}" \
+        #  --arg jobName "${CIRCLE_JOB}" \
+        #  --arg buildNumber "${CIRCLE_BUILD_NUM}" \
+        #  --arg url "${CIRCLE_BUILD_URL}" \
+        #  --arg workflowUrl "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
+        #  --arg commit "${CIRCLE_SHA1}" \
+        #  --arg refUri "${CIRCLE_REPOSITORY_URL}/tree/${CIRCLE_BRANCH}" \
+        #  --arg repositoryUri "${CIRCLE_REPOSITORY_URL}" \
+        #  --arg branchName "${CIRCLE_BRANCH}" \
+        #  --arg workflowId "${CIRCLE_WORKFLOW_ID}" \
+        #  --arg repoName "${CIRCLE_PROJECT_REPONAME}" \
+        #  --arg display "${CIRCLE_PROJECT_REPONAME}"  \
+        #  --arg description "${CIRCLE_PROJECT_REPONAME} #${CIRCLE_BUILD_NUM} ${CIRCLE_JOB}" \
+        #  --argjson issueKeys "${ISSUE_KEYS}" \
+        #  '
+        #  ($time_str | tonumber) as $time_num |
+        #  {
+        #    "builds": [
+        #      {
+        #        "schemaVersion": "1.0",
+        #        "pipelineId": $projectName,
+        #        "buildNumber": $pipelineNumber,
+        #        "updateSequenceNumber": $time_str,
+        #        "displayName": $display,
+        #        "description": $description,
+        #        "url": $workflowUrl,
+        #        "state": $state,
+        #        "lastUpdated": $lastUpdated,
+        #        "issueKeys": $issueKeys
+        #      }
+        #    ]
+        #  }
+        #  ' > /tmp/jira-status.json
+        #}
+
+
+        #generate_json_payload_deployment () {
+        #  echo "Update Jira with status: ${JIRA_BUILD_STATUS} for ${CIRCLE_PIPELINE_NUMBER}"
+        #  iso_time=$(date '+%Y-%m-%dT%T%z'| sed -e 's/\([0-9][0-9]\)$/:\1/g')
+        #  echo {} | jq \
+        #  --arg time_str "$(date +%s)" \
+        #  --arg lastUpdated "${iso_time}" \
+        #  --arg state "${JIRA_BUILD_STATUS}" \
+        #  --arg buildNumber "${CIRCLE_BUILD_NUM}" \
+        #  --arg pipelineNumber "${CIRCLE_PIPELINE_NUMBER}" \
+        #  --arg projectName "${CIRCLE_PROJECT_REPONAME}" \
+        #  --arg url "${CIRCLE_BUILD_URL}" \
+        #  --arg commit "${CIRCLE_SHA1}" \
+        #  --arg refUri "${CIRCLE_REPOSITORY_URL}/tree/${CIRCLE_BRANCH}" \
+        #  --arg repositoryUri "${CIRCLE_REPOSITORY_URL}" \
+        #  --arg branchName "${CIRCLE_BRANCH}" \
+        #  --arg workflowId "${CIRCLE_WORKFLOW_ID}" \
+        #  --arg workflowUrl "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}" \
+        #  --arg repoName "${CIRCLE_PROJECT_REPONAME}" \
+        #  --arg pipelineDisplay "#${CIRCLE_PIPELINE_NUMBER} ${CIRCLE_PROJECT_REPONAME}"  \
+        #  --arg deployDisplay "#${CIRCLE_PIPELINE_NUMBER}  ${CIRCLE_PROJECT_REPONAME} - <<parameters.environment>>"  \
+        #  --arg description "${CIRCLE_PROJECT_REPONAME} #${CIRCLE_PIPELINE_NUMBER} ${CIRCLE_JOB} <<parameters.environment>>" \
+        #  --arg envId "${CIRCLE_WORKFLOW_ID}-<<parameters.environment>>" \
+        #  --arg envName "<<parameters.environment>>" \
+        #  --arg envType "<<parameters.environment_type>>" \
+        #  --argjson issueKeys "${ISSUE_KEYS}" \
+        #  '
+        #  ($time_str | tonumber) as $time_num |
+        #  {
+        #    "deployments": [
+        #      {
+        #        "schemaVersion": "1.0",
+        #        "pipeline": {
+        #          "id": $repoName,
+        #          "displayName": $pipelineDisplay,
+        #          "url": $workflowUrl
+        #        },
+        #        "deploymentSequenceNumber": $pipelineNumber,
+        #        "updateSequenceNumber": $time_str,
+        #        "displayName": $deployDisplay,
+        #        "description": $description,
+        #        "url": $url,
+        #        "state": $state,
+        #        "lastUpdated": $lastUpdated,
+        #        "associations": [
+        #          {
+        #            "associationType": "issueKeys",
+        #            "values": $issueKeys
+        #          },
+        #          {
+        #            "associationType": "serviceIdOrKeys",
+        #            "values": ["<< parameters.service_id >>"]
+        #          }
+        #        ],
+        #        "environment":{
+        #          "id": $envId,
+        #          "displayName": $envName,
+        #          "type": $envType
+        #        }
+        #      }
+        #    ]
+        #  }
+        #  ' > /tmp/jira-status.json
+        #}
 
 
 
-        post_to_jira () {
-          HTTP_STATUS=$(curl \
-          -u "${<<parameters.token_name>>}:" \
-          -s -w "%{http_code}" -o /tmp/curl_response.txt \
-          -H "Content-Type: application/json" \
-          -H "Accept: application/json" \
-          -X POST "https://circleci.com/api/v1.1/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/jira/<<parameters.job_type>>" --data @/tmp/jira-status.json)
+        #post_to_jira () {
+        #  HTTP_STATUS=$(curl \
+        #  -u "${<<parameters.token_name>>}:" \
+        #  -s -w "%{http_code}" -o /tmp/curl_response.txt \
+        #  -H "Content-Type: application/json" \
+        #  -H "Accept: application/json" \
+        #  -X POST "https://circleci.com/api/v1.1/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/jira/<<parameters.job_type>>" --data @/tmp/jira-status.json)
 
-          echo "Results from Jira: "
-          if [ "${HTTP_STATUS}" != "200" ];then
-            echo "Error calling Jira, result: ${HTTP_STATUS}" >&2
-            jq '.' /tmp/curl_response.txt
-            exit 0
-          fi
+        #  echo "Results from Jira: "
+        #  if [ "${HTTP_STATUS}" != "200" ];then
+        #    echo "Error calling Jira, result: ${HTTP_STATUS}" >&2
+        #    jq '.' /tmp/curl_response.txt
+        #    exit 0
+        #  fi
 
-          case "<<parameters.job_type>>" in
-            "build")
-              if jq -e '.unknownIssueKeys[0]' /tmp/curl_response.txt > /dev/null; then
-                echo "ERROR: unknown issue key"
-                jq '.' /tmp/curl_response.txt
-                exit 0
-              fi
-            ;;
-            "deployment")
-              if jq -e '.unknownAssociations[0]' /tmp/curl_response.txt > /dev/null; then
-                echo "ERROR: unknown association"
-                jq '.' /tmp/curl_response.txt
-                exit 0
-              fi
-              if jq -e '.rejectedDeployments[0]' /tmp/curl_response.txt > /dev/null; then
-                echo "ERROR: Deployment rejected"
-                jq '.' /tmp/curl_response.txt
-                exit 0
-              fi
-            ;;
-          esac
+        #  case "<<parameters.job_type>>" in
+        #    "build")
+        #      if jq -e '.unknownIssueKeys[0]' /tmp/curl_response.txt > /dev/null; then
+        #        echo "ERROR: unknown issue key"
+        #        jq '.' /tmp/curl_response.txt
+        #        exit 0
+        #      fi
+        #    ;;
+        #    "deployment")
+        #      if jq -e '.unknownAssociations[0]' /tmp/curl_response.txt > /dev/null; then
+        #        echo "ERROR: unknown association"
+        #        jq '.' /tmp/curl_response.txt
+        #        exit 0
+        #      fi
+        #      if jq -e '.rejectedDeployments[0]' /tmp/curl_response.txt > /dev/null; then
+        #        echo "ERROR: Deployment rejected"
+        #        jq '.' /tmp/curl_response.txt
+        #        exit 0
+        #      fi
+        #    ;;
+        #  esac
 
-          # If reached this point, the deployment was a success.
-          echo
-          jq '.' /tmp/curl_response.txt
-          echo
-          echo
-          echo "Success!"
-        }
+        #  # If reached this point, the deployment was a success.
+        #  echo
+        #  jq '.' /tmp/curl_response.txt
+        #  echo
+        #  echo
+        #  echo "Success!"
+        #}
 
 
-        # kick off
+        ## kick off
 
-        source <<parameters.state_path>>
+        #source <<parameters.state_path>>
 
-        run
+        #run
 
-        rm -f <<parameters.state_path>>
+        #rm -f <<parameters.state_path>>
       name: Update status in Atlassian Jira
       when: always
